---
- name: Install Collectd and RRDTool
  apt: name={{ item }} state=latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify: reload systemd
  with_items:
    - librrds-perl
    - collectd
    - rrdtool
    
- name: Install Collectd and RRDTool
  yum: name={{ item }} state=latest
  when: ansible_distribution == 'CentOS'
  notify: reload systemd
  with_items:
    - collectd
    - rrdtool
    - rrdtool-devel

- name: Configure Collectd
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  template: src=../templates/collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify: restart collectd

- name: Configure Collectd
  when: ansible_distribution == 'CentOS'
  template: src=../templates/collectd.conf.j2 dest=/etc/collectd.conf
  notify: restart collectd
