### openwisp2
## tasks
- include: apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: [openwisp2, apt]
  
- include: yum.yml
  when: ansible_distribution == 'CentOS'
  tags: [openwisp2, yum]

- include: pip.yml
  tags: [openwisp2, pip]
  
- include: collectd.yml
  tags: [openwisp2, collectd]

# comprises django_secret_key.yml
- include: django.yml
  tags: [openwisp2, django]

- include: supervisor.yml
  tags: [openwisp2, supervisor]

- include: nginx.yml
  tags: [openwisp2, nginx]
