- name: Dealing with permissions for {{ openwisp2_path }}/log and SELinux
  when: ansible_distribution == 'CentOS'
  shell: {{ item }}
  with_items:
  - chown -R www-data:www-data {{ openwisp2_path }}/log
  - ausearch -c 'nginx' --raw | audit2allow -M my-nginx
  - semodule -i my-nginx.pp
  - setsebool -P httpd_can_network_connect 1

- name: nginx configuration
  when: ansible_distribution == 'CentOS'
  action: template src=../templates/nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: create "{{ openwisp2_path }}/public_html"
  file:
    path: "{{ openwisp2_path }}/public_html"
    state: directory

- name: create "{{ openwisp2_path }}/ssl"
  file:
    path: "{{ openwisp2_path }}/ssl"
    state: directory

- name: create SSL cert if not exists yet
  command: >
    openssl req -new -nodes -x509 -subj "/C={{ openwisp2_ssl_country }}/ST={{ openwisp2_ssl_state }}/L={{ openwisp2_ssl_locality }}/O={{ openwisp2_ssl_organization }}/CN={{ openwisp2_ssl_common_name }}" -days 3650 -keyout {{ openwisp2_ssl_key }} -out {{ openwisp2_ssl_cert }} -extensions v3_ca creates={{ openwisp2_ssl_cert }}
  notify: restart nginx
  
- name: create sites-available directory
  when: ansible_distribution == 'CentOS'
  file:
    path: "/etc/nginx/sites-available/"
    state: directory
    group: www-data
    mode: 0775
    
- name: create sites-enabled directory
  when: ansible_distribution == 'CentOS'
  file:
    path: "/etc/nginx/sites-enabled/"
    state: directory
    group: www-data
    mode: 0775

- name: nginx site available
  template:
    src: ../templates/nginx.j2
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}"
  notify: restart nginx

- name: nginx site enabled
  file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link
  notify: restart nginx
