- name: Update pip & related tools
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - pip
    - setuptools
    - wheel

- name: Install stable version of django-netjsonconfig
  when: openwisp2_stable
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - django-netjsonconfig
    - "https://github.com/DimPolissiou/django-actions/raw/master/django-actions-priv-0.0.10-py2.py3-none-any.whl"
    - "git+git://github.com/DimPolissiou/django-devices#egg=django-devices"
  notify: reload supervisor

- name: Install development version of django-netjsonconfig
  when: not openwisp2_stable
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - "git+git://github.com/openwisp/django-netjsonconfig#egg=django-netjsonconfig"
    - "https://github.com/DimPolissiou/django-actions/raw/master/django-actions-priv-0.0.10-py2.py3-none-any.whl"
    - "git+git://github.com/DimPolissiou/django-devices#egg=django-devices"
  notify: reload supervisor

- name: Install development version of netjsonconfig
  when: not openwisp2_netjsonconfig_stable
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - "git+git://github.com/openwisp/netjsonconfig#egg=netjsonconfig"
    - "https://github.com/DimPolissiou/django-actions/raw/master/django-actions-priv-0.0.10-py2.py3-none-any.whl"
    - "git+git://github.com/DimPolissiou/django-devices#egg=django-devices"
  notify: reload supervisor

- name: Install extra django apps
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items: "{{ openwisp2_extra_django_apps }}"
  notify: reload supervisor

- name: Install uwsgi
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - uwsgi
  notify: reload supervisor

- name: Install psycopg2
  when: openwisp2_database.engine in ["django.db.backends.postgresql", "django.contrib.gis.db.backends.postgis"]
  pip:
    name: psycopg2
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install MySQL-python
  when: openwisp2_database.engine in ["django.db.backends.mysql", "django.contrib.gis.db.backends.mysql"]
  pip:
    name: MySQL-python
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install raven (sentry client)
  when: openwisp2_sentry.get('dsn') != False
  pip:
    name: raven
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor
