### openwisp2
## handlers
---

- name: reload systemd
  shell: systemctl daemon-reload
  when: ansible_distribution_release in ['jessie', 'xenial', 'CentOS']

- name: reload supervisor
  shell: supervisorctl reload

- name: restart nginx
  service: name=nginx state=restarted

- name: restart collectd
  service: name=collectd state=restarted
  tags:
    - collectd
