### openwisp2
## handlers
---

- name: reload systemd
  shell: systemctl daemon-reload
  when: ansible_distribution_release in ['jessie', 'xenial']

- name: reload supervisor
  shell: supervisorctl reload

- name: restart nginx
  service: name=nginx state=restarted

- name: "Restart collectd"
  service: >
    name=collectd
    state=restarted
  tags:
    - collectd
